package constant

object Constants {
  var JDBC_DRIVER = "jdbc.driver"
  var JDBC_DATASOURCE_SIZE="jdbc.datasource.size"
  var JDBC_URL="jdbc.url"
  var JDBC_USER="jdbc.user"
  var JDBC_PASSWORD="jdbc.password"
  var SPARK_LOCAL = "spark.local"
  var SPARK_APP_NAME = "UserVisitSessionAnalyzeSpark"
  var PARAM_START_DATE = "startDate"
  var PARAM_END_DATE = "endDate"
  var FIELD_SESSION_ID = "sessionid"
  var FIELD_SEARCH_KEYWORDS = "searchKeywords"
  var FIELD_CLICK_CATEGORY_IDS = "clickCategoryIds"
  var FIELD_AGE = "age"
  var FIELD_PROFESSIONAL = "professional"
  var FIELD_CITY = "city"
  var FIELD_SEX = "sex"
  var PARAM_START_AGE = "startAge"
  var PARAM_END_AGE = "endage"
  var PARAM_PROFESSIONALS = "professionals"
  var PARAM_CITIES = "cities"
  var PARAM_SEX = "sex"
  var PARAM_KEYWORDS = "keywords"
  var PARAM_CATEGORY_IDS = "categoryIds"
  var SESSION_COUNT = "session_count"
  var TIME_PERIOD_1s_3s = "1s_3s"
  var TIME_PERIOD_4s_6s = "4s_6s"
  var TIME_PERIOD_7s_9s = "7s_9s"
  var TIME_PERIOD_10s_30s = "10s_30s"
  var TIME_PERIOD_30s_60s = "30s_60s"
  var TIME_PERIOD_1m_3m = "1m_3m"
  var TIME_PERIOD_3m_10m = "3m_10m"
  var TIME_PERIOD_10m_30m = "10m_30m"
  var TIME_PERIOD_30m = "30m"
  var STEP_PERIOD_1_3 = "1_3"
  var STEP_PERIOD_4_6 = "4_6"
  var STEP_PERIOD_7_9 = "7_9"
  var STEP_PERIOD_10_30 = "10_30"
  var STEP_PERIOD_30_60 = "30_60" 
  var STEP_PERIOD_60 = "60"

}
